#
# This file is automatically generated from Random.idl
# by idl2tcl. Do not edit.
#

set _ir_Random \
{{interface {IDL:Random:1.0 Random 1.0} {} {{operation\
{IDL:Random/lrand48:1.0 lrand48 1.0} long {} {}} {operation\
{IDL:Random/mrand48:1.0 mrand48 1.0} long {} {}}}}}

#
# This is just to clear the interp from the ridiculously long string above
#

expr 1

